### PR TITLE
allow custom message for android on show

### PR DESCRIPTION
**Pull request by NathanWalker**
One more thing :+1:

### CODE REVIEW

**Comment by maknz** [comment]
Ideally we'd need a cross-platform way to do this.

**Comment by NathanWalker** [comment]
The api's are different in this regard. Since with iOS, you configure the instance after creation. With Android it can be passed in. To make the JS api the same we could configure the instance inside js like this:

```
indicator.show = function(msg) {
  var hud = MBProgressHUD.showHUDAddedToAnimated(this._getRootWindow(), true);
  hud.labelText = msg || 'Loading';
  return hud;
};
```

Thoughts?

**Comment by maknz** [comment]
:+1: from me.

I think we should have the argument to the `show` as an object so we can extend it with further options in the future without breaking the API.

``` js
var loader = loader.show({
  message: "Hello"
});
```

lodash has some good utility functions for handling object merges with defaults and such, although unnecessary at this point.

**Comment by NathanWalker** [comment]
I have something really nice in the works here and will submit a different PR for it when it's ready this week :+1:

**Pull request closed without merging**
